// Generated by CoffeeScript 1.9.1
(function() {
  (function($) {
    var Methods;
    Methods = (function() {
      function Methods() {}

      Methods.prototype.init = function(options) {
        var defaults, settings;
        defaults = {
          name: "dname",
          age: 10,
          sex: "female"
        };
        settings = $.extend({}, defaults, options);
        console.log(defaults);
      };

      Methods.prototype.show = function() {
        return console.log("show function");
      };

      Methods.prototype.hide = function() {
        return console.log("hide function");
      };

      return Methods;

    })();
    return $.fn.myPlugin = function(method) {
      var methods;
      methods = new Methods;
      if (methods[method]) {
        return methods[method].apply(this, Array.prototype.slice(arguments, 1));
      } else if (typeof method === "object") {
        return methods.init.call(this, arguments);
      } else {
        return $.error('methods #{method} does not exit');
      }
    };
  })(jQuery);

}).call(this);
